# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_maze": "boards.ipynb",
         "shame_game": "boards.ipynb",
         "plot_boards": "plots.ipynb",
         "plain_game": "boards.ipynb",
         "available_moves": "boards.ipynb",
         "plot_maze": "plots.ipynb",
         "plot_historgrams": "plots.ipynb",
         "plot_available": "plots.ipynb"}

modules = ["boards.py",
           "plots.py"]

doc_url = "https://parenthetical-e.github.io/truthiness/"

git_url = "https://github.com/parenthetical-e/truthiness/tree/master/"

def custom_doc_links(name): return None
