# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Base": "gym.ipynb",
         "ShameGame1": "gym.ipynb",
         "PlainGame1": "gym.ipynb",
         "run": "player.ipynb",
         "save_table": "player.ipynb",
         "extract_moves": "player.ipynb",
         "extract_board": "player.ipynb",
         "move_filter": "player.ipynb",
         "Random": "player.ipynb",
         "Curious": "player.ipynb",
         "CuriousMCTS": "player.ipynb",
         "Sensitive": "player.ipynb",
         "SensitiveMCTS": "player.ipynb",
         "Evil": "player.ipynb",
         "EvilMCTS": "player.ipynb",
         "OptimalForage": "player.ipynb",
         "OptimalForageMCTS": "player.ipynb",
         "plot_maze": "plot.ipynb",
         "plot_boards": "plot.ipynb",
         "plot_histograms": "plot.ipynb",
         "plot_available": "plot.ipynb"}

modules = ["gym.py",
           "player.py",
           "plot.py"]

doc_url = "https://parenthetical-e.github.io/truthiness/"

git_url = "https://github.com/parenthetical-e/truthiness/tree/master/"

def custom_doc_links(name): return None
