# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_maze": "game.ipynb",
         "shame_game": "game.ipynb",
         "plot_boards": "plot.ipynb",
         "plain_game": "game.ipynb",
         "random_move": "game.ipynb",
         "available_moves": "game.ipynb",
         "Base": "gym.ipynb",
         "ShameGame1": "gym.ipynb",
         "PlainGame1": "gym.ipynb",
         "run": "player.ipynb",
         "Random": "player.ipynb",
         "plot_maze": "plot.ipynb",
         "plot_histograms": "plot.ipynb",
         "plot_available": "plot.ipynb"}

modules = ["game.py",
           "gym.py",
           "player.py",
           "plot.py"]

doc_url = "https://parenthetical-e.github.io/truthiness/"

git_url = "https://github.com/parenthetical-e/truthiness/tree/master/"

def custom_doc_links(name): return None
